import java.util.*;

public class MovieSeederWithYoutube {
        public static void seedMovies(FilmController controller) {
             Movie[] movies = new Movie[] {
                                new Movie("Warfare", Arrays.asList("War", "Action"), "Unknown", Arrays.asList(), 2025,
                                                "Warfare",
                                                "A platoon of Navy SEALs embarks on a dangerous mission in Ramadi, Iraq, with the chaos and brotherhood of war retold through their memories of the event.",
                                                "en", "2025-01-01", 7.223, 197, "/j8tqBXwH2PxBPzbtO19BTF9Ukbf.jpg",
                                                "/cJvUJEEQ86LSjl4gFLkYpdCJC96.jpg", 524.0776,
                                                "https://www.imdb.com/find?q=Warfare+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Warfare+trailer"),
                                new Movie("Exterritorial", Arrays.asList("Thriller", "Action"), "Unknown", Arrays.asList(), 2025,
                                                "Exterritorial",
                                                "When her son vanishes inside a US consulate, ex-special forces soldier Sara does everything in her power to find him — and uncovers a dark conspiracy.",
                                                "de", "2025-01-01", 6.631, 263, "/jM2uqCZNKbiyStyzXOERpMqAbdx.jpg",
                                                "/bVm6udIB6iKsRqgMdQh6HywuEBj.jpg", 391.7688,
                                                "https://www.imdb.com/find?q=Exterritorial+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Exterritorial+trailer"),
                                new Movie("Thunderbolts*", Arrays.asList("Action", "Adventure", "Science Fiction"), "Unknown", Arrays.asList(), 2025,
                                                "Thunderbolts*",
                                                "After finding themselves ensnared in a death trap, seven disillusioned castoffs must embark on a dangerous mission that will force them to confront the darkest corners of their pasts.",
                                                "en", "2025-01-01", 7.548, 715, "/m9EtP1Yrzv6v7dMaC9mRaGhd1um.jpg",
                                                "/rthMuZfFv4fqEU4JVbgSW9wQ8rs.jpg", 383.6091,
                                                "https://www.imdb.com/find?q=Thunderbolts%2A+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Thunderbolts*+trailer"),
                                new Movie("Last Bullet", Arrays.asList("Action", "Crime", "Thriller"), "Unknown", Arrays.asList(), 2025,
                                                "Balle perdue 3",
                                                "Car genius Lino returns to conclude his vendetta against Areski and the corrupt commander who ruined their lives in this turbo-charged trilogy finale.",
                                                "fr", "2025-01-01", 6.946, 56, "/qycPITRqXgPai7zj1gKffjCdSB5.jpg",
                                                "/4A5HH9HkCPqAwyYL6CnA0mxbYjn.jpg", 381.5997,
                                                "https://www.imdb.com/find?q=Last+Bullet+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Last+Bullet+trailer"),
                                new Movie("A Working Man", Arrays.asList("Action", "Crime", "Thriller"), "Unknown", Arrays.asList(), 2025,
                                                "A Working Man",
                                                "Levon Cade left behind a decorated military career in the black ops to live a simple life working construction. But when his boss's daughter, who is like family to him, is taken by human traffickers, his search to bring her home uncovers a world of corruption far greater than he ever could have imagined.",
                                                "en", "2025-01-01", 6.51, 608, "/6FRFIogh3zFnVWn7Z6zcYnIbRcX.jpg",
                                                "/fTrQsdMS2MUw00RnzH0r3JWHhts.jpg", 329.0393,
                                                "https://www.imdb.com/find?q=A+Working+Man+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=A+Working+Man+trailer"),
                                new Movie("Rust", Arrays.asList("Western"), "Unknown", Arrays.asList(), 2025, "Rust",
                                                "Infamous outlaw Harland Rust breaks his estranged grandson Lucas out of prison, after Lucas is convicted to hang for an accidental murder. The two must outrun legendary U.S Marshal Wood Helm and bounty hunter Fenton \"Preacher\" Lang who are hot on their tails. Deeply buried secrets rise from the ashes and an unexpected familial bond begins to form as the mismatched duo tries to survive the merciless American Frontier.",
                                                "en", "2025-01-01", 6.3, 35, "/tbJ3RkA2s6X5qrBzrYHYTxvDBui.jpg",
                                                "/12tEzU0bNYKIjXXEwI5abuOotHF.jpg", 280.1126,
                                                "https://www.imdb.com/find?q=Rust+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Rust+trailer"),
                                new Movie("A Minecraft Movie", Arrays.asList("Family", "Comedy", "Adventure", "Fantasy"), "Unknown", Arrays.asList(),
                                                2025, "A Minecraft Movie",
                                                "Four misfits find themselves struggling with ordinary problems when they are suddenly pulled through a mysterious portal into the Overworld: a bizarre, cubic wonderland that thrives on imagination. To get back home, they'll have to master this world while embarking on a magical quest with an unexpected, expert crafter, Steve.",
                                                "en", "2025-01-01", 6.154, 853, "/iPPTGh2OXuIv6d7cwuoPkw8govp.jpg",
                                                "/2Nti3gYAX513wvhp8IiLL6ZDyOm.jpg", 276.7775,
                                                "https://www.imdb.com/find?q=A+Minecraft+Movie+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=A+Minecraft+Movie+trailer"),
                                new Movie("Captain America: Brave New World", Arrays.asList("Action", "Thriller", "Science Fiction"), "Unknown",
                                                Arrays.asList(), 2025, "Captain America: Brave New World",
                                                "After meeting with newly elected U.S. President Thaddeus Ross, Sam finds himself in the middle of an international incident. He must discover the reason behind a nefarious global plot before the true mastermind has the entire world seeing red.",
                                                "en", "2025-01-01", 6.139, 1792, "/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg",
                                                "/8eifdha9GQeZAkexgtD45546XKx.jpg", 209.6215,
                                                "https://www.imdb.com/find?q=Captain+America%3A+Brave+New+World+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Captain+America:+Brave+New+World+trailer"),
                                new Movie("Tarzan", Arrays.asList("Family", "Adventure", "Animation", "Drama"), "Unknown", Arrays.asList(), 1999,
                                                "Tarzan",
                                                "Tarzan was a small orphan who was raised by an ape named Kala since he was a child. He believed that this was his family, but on an expedition Jane Porter is rescued by Tarzan. He then finds out that he's human. Now Tarzan must make the decision as to which family he should belong to...",
                                                "en", "1999-01-01", 7.396, 6925, "/bTvHlcqiOjGa3lFtbrTLTM3zasY.jpg",
                                                "/86z1Yrwj7yN1xehSa0gIwHnR7xl.jpg", 146.0758,
                                                "https://www.imdb.com/find?q=Tarzan+1999&s=tt",
                                                "https://www.youtube.com/results?search_query=Tarzan+trailer"),
                                new Movie("Brave Citizen", Arrays.asList("Action", "Drama", "Comedy"), "Unknown", Arrays.asList(), 2023,
                                                "용감한 시민",
                                                "An expelled boxing champion, who now is a high-school teacher, witnesses intolerable violence and throws her first punch to build justice against it, while putting on a mask.",
                                                "ko", "2023-01-01", 7.1, 35, "/ixQoOExnnvIxYvnqGgfhaWqXeXc.jpg",
                                                "/9yMmIou6xMtw2A61xiMsEcAhTrL.jpg", 219.187,
                                                "https://www.imdb.com/find?q=Brave+Citizen+2023&s=tt",
                                                "https://www.youtube.com/results?search_query=Brave+Citizen+trailer"),
                                new Movie("Havoc", Arrays.asList("Action", "Crime", "Thriller"), "Unknown", Arrays.asList(), 2025, "Havoc",
                                                "When a drug heist swerves lethally out of control, a jaded cop fights his way through a corrupt city's criminal underworld to save a politician's son.",
                                                "en", "2025-01-01", 6.5, 572, "/r46leE6PSzLR3pnVzaxx5Q30yUF.jpg",
                                                "/65MVgDa6YjSdqzh7YOA04mYkioo.jpg", 188.7515,
                                                "https://www.imdb.com/find?q=Havoc+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Havoc+trailer"),
                                new Movie("Jewel Thief: The Heist Begins", Arrays.asList("Action", "Thriller"), "Unknown",
                                                Arrays.asList(), 2025, "ज्वेल थीफ: द हीस्ट बिगिन्स",
                                                "In this high-octane battle of wits and wills, ingenious con artist Rehan devises a diamond heist while trying to outsmart Rajan, his sadistic adversary.",
                                                "hi", "2025-01-01", 6.557, 36, "/eujLbO0kf1eqWC8XpHUJdtAVW2J.jpg",
                                                "/kFXtAwJYbRTqiyQpE9kDc8qEP3X.jpg", 151.1606,
                                                "https://www.imdb.com/find?q=Jewel+Thief%3A+The+Heist+Begins+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Jewel+Thief:+The+Heist+Begins+trailer"),
                                new Movie("Death of a Unicorn", Arrays.asList("Horror", "Fantasy", "Comedy", "Adventure", "Science Fiction"), "Unknown", Arrays.asList(),
                                                2025, "Death of a Unicorn",
                                                "A father and daughter accidentally hit and kill a unicorn while en route to a weekend retreat, where his billionaire boss seeks to exploit the creature’s miraculous curative properties.",
                                                "en", "2025-01-01", 6.478, 182, "/lXR32JepFwD1UHkplWqtBP1K79z.jpg",
                                                "/eDBZN0TbWkxoAB0qIDFagVcPPTN.jpg", 177.0844,
                                                "https://www.imdb.com/find?q=Death+of+a+Unicorn+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Death+of+a+Unicorn+trailer"),
                                new Movie("The Accountant", Arrays.asList("Crime", "Thriller", "Drama"), "Unknown", Arrays.asList(), 2016,
                                                "The Accountant",
                                                "As a math savant uncooks the books for a new client, the Treasury Department closes in on his activities and the body count starts to rise.",
                                                "en", "2016-01-01", 7.102, 6531, "/fceheXB5fC4WrLVuWJ6OZv9FXYr.jpg",
                                                "/dTGECn8He16tZeBHQTLf6rVydE8.jpg", 251.5226,
                                                "https://www.imdb.com/find?q=The+Accountant+2016&s=tt",
                                                "https://www.youtube.com/results?search_query=The+Accountant+trailer"),
                                new Movie("Bad Influence", Arrays.asList("Thriller", "Drama", "Romance"), "Unknown", Arrays.asList(), 2025,
                                                "Mala influencia",
                                                "An ex-con gets a fresh start when hired to protect a wealthy heiress from a stalker — but their chemistry is hard to resist as they grow closer.",
                                                "es", "2025-01-01", 6.195, 41, "/ghhooCOqQDqC6vhS1SVN2tCE0k8.jpg",
                                                "/zXUxcXnBPHF1cD0IHi4KUpsNvF4.jpg", 154.8636,
                                                "https://www.imdb.com/find?q=Bad+Influence+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Bad+Influence+trailer"),
                                new Movie("In the Lost Lands", Arrays.asList("Action", "Fantasy", "Adventure"), "Unknown", Arrays.asList(),
                                                2025, "In the Lost Lands",
                                                "A queen sends the powerful and feared sorceress Gray Alys to the ghostly wilderness of the Lost Lands in search of a magical power, where she and her guide, the drifter Boyce, must outwit and outfight both man and demon.",
                                                "en", "2025-01-01", 6.325, 348, "/dDlfjR7gllmr8HTeN6rfrYhTdwX.jpg",
                                                "/op3qmNhvwEvyT7UFyPbIfQmKriB.jpg", 178.8997,
                                                "https://www.imdb.com/find?q=In+the+Lost+Lands+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=In+the+Lost+Lands+trailer"),
                                new Movie("Conjuring the Cult", Arrays.asList("Horror", "Drama"), "Unknown", Arrays.asList(),
                                                2024, "Conjuring the Cult",
                                                "After discovering his blood-soaked daughter dead in the bathtub, David Bryson attends a self-help group to help save him from his ghostly nightmares. But when a group of mysterious cult-like women offer to help him resurrect his daughter. David's choices will not just decide his fate... but the fate of his dead daughter's SOUL.",
                                                "en", "2024-01-01", 3.75, 12, "/t4MiAeYpjL7saYvqvcn9xtOfA4K.jpg",
                                                "/mrmaTVp7PTBkjj5G62cE9pjrENg.jpg", 188.5559,
                                                "https://www.imdb.com/find?q=Conjuring+the+Cult+2024&s=tt",
                                                "https://www.youtube.com/results?search_query=Conjuring+the+Cult+trailer"),
                                new Movie("Sinners", Arrays.asList("Action", "Horror", "Thriller"), "Unknown", Arrays.asList(), 2025,
                                                "Sinners",
                                                "Trying to leave their troubled lives behind, twin brothers return to their hometown to start again, only to discover that an even greater evil is waiting to welcome them back.",
                                                "en", "2025-01-01", 7.594, 647, "/jYfMTSiFFK7ffbY2lay4zyvTkEk.jpg",
                                                "/nAxGnGHOsfzufThz20zgmRwKur3.jpg", 143.2531,
                                                "https://www.imdb.com/find?q=Sinners+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Sinners+trailer"),
                                new Movie("Van Gogh by Vincent", Arrays.asList("Documentary"), "Unknown", Arrays.asList(),
                                                2025, "Van Gogh by Vincent",
                                                "In a career that lasted only ten years, Vincent Van Gogh painted one subject more than any other: himself. This is the story of Vincent told using eight of his most iconic self-portraits.",
                                                "fr", "2025-01-01", 6.4, 14, "/z73X4WKZghBh5fri31o8P6vBEB2.jpg",
                                                "/1AWjIUgbZYaKbwUH5qoJaKCcRkf.jpg", 139.6056,
                                                "https://www.imdb.com/find?q=Van+Gogh+by+Vincent+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Van+Gogh+by+Vincent+trailer"),
                                new Movie("Saint Catherine", Arrays.asList("Horror"), "Unknown", Arrays.asList(), 2024,
                                                "Saint Catherine",
                                                "An orphaned girl is rescued from a satanic ritual and taken to Saint Catherine Institute for homeless youth. There she will learn new skills while facing demons that stalk her.",
                                                "en", "2024-01-01", 6.34, 25, "/hBJdzKPeDaC96AzlrtMWBomYSZV.jpg",
                                                "/svLj9iyRmmeNVRsMreANn7DPPZE.jpg", 139.6035,
                                                "https://www.imdb.com/find?q=Saint+Catherine+2024&s=tt",
                                                "https://www.youtube.com/results?search_query=Saint+Catherine+trailer"),
                                new Movie("Stream", Arrays.asList("Horror"), "Unknown", Arrays.asList(), 2024,
                                                "Stream",
                                                "Craven, a streamer with thousands of followers on a live streaming platform, has prepared a very special stream for Halloween. What no one expects when reacting to a video of Pentagram, a group of young paranormal investigators, is that the live experience will turn into the worst night of their lives. And maybe... the last.",
                                                "es", "2024-01-01", 6.25, 2, "/aqLBOmJ59FdEMXARmpDnwHrcfV2.jpg",
                                                "/jI8j3vy1fFZpjaGA6ALuyQuadfm.jpg", 145.2046,
                                                "https://www.imdb.com/find?q=Stream+2024&s=tt",
                                                "https://www.youtube.com/results?search_query=Stream+trailer"),
                                new Movie("Laila", Arrays.asList("Comedy", "Romance"), "Unknown", Arrays.asList(), 2025, "లైలా",
                                                "Sonu Model, a renowned beautician from the old city, is forced to disguise himself as Laila, leading to a series of comedic, romantic, and action-packed events. Chaos ensues in this hilarious laugh riot",
                                                "te", "2025-01-01", 5.0, 3, "/l4gsNxFPGpzbq0D6QK1a8vO1lBz.jpg",
                                                "/vNUwK5P42m81uG57kKI1WxSZwIQ.jpg", 120.501,
                                                "https://www.imdb.com/find?q=Laila+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Laila+trailer"),
                                new Movie("Black Widow", Arrays.asList("Action", "Adventure", "Science Fiction"), "Unknown", Arrays.asList(), 2021,
                                                "Black Widow",
                                                "Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.",
                                                "en", "2021-01-01", 7.208, 10519, "/kwB7d51AIcyzPOBOHLCEZJkmPhQ.jpg",
                                                "/6azpBJGcLx9SKif8h9VMnflBfa.jpg", 98.4002,
                                                "https://www.imdb.com/find?q=Black+Widow+2021&s=tt",
                                                "https://www.youtube.com/results?search_query=Black+Widow+trailer"),
                                new Movie("Another Simple Favor", Arrays.asList("Thriller", "Comedy", "Crime"), "Unknown", Arrays.asList(),
                                                2025, "Another Simple Favor",
                                                "Stephanie and Emily reunite on the beautiful island of Capri, Italy for Emily's extravagant wedding to a rich Italian businessman. Along with the glamorous guests, expect murder and betrayal to RSVP for a wedding with more twists and turns than the road from the Marina Grande to the Capri town square.",
                                                "en", "2025-01-01", 6.1, 205, "/zboCGZ4aIqPMd7VFI4HWnmc7KYJ.jpg",
                                                "/b6e5Nss2QNoQM4wJv2VppChswNP.jpg", 112.6984,
                                                "https://www.imdb.com/find?q=Another+Simple+Favor+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Another+Simple+Favor+trailer"),
                                new Movie("The Monkey", Arrays.asList("Horror", "Comedy"), "Unknown", Arrays.asList(), 2025,
                                                "The Monkey",
                                                "When twin brothers find a mysterious wind-up monkey, a series of outrageous deaths tear their family apart. Twenty-five years later, the monkey begins a new killing spree forcing the estranged brothers to confront the cursed toy.",
                                                "en", "2025-01-01", 5.885, 595, "/yYa8Onk9ow7ukcnfp2QWVvjWYel.jpg",
                                                "/6dC7ULfiutxwEAs7LjWHL2Tc7Zv.jpg", 126.8067,
                                                "https://www.imdb.com/find?q=The+Monkey+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=The+Monkey+trailer"),
                                new Movie("Conclave", Arrays.asList("Drama", "Thriller", "Mystery"), "Unknown", Arrays.asList(), 2024,
                                                "Conclave",
                                                "After the unexpected death of the Pope, Cardinal Lawrence is tasked with managing the covert and ancient ritual of electing a new one. Sequestered in the Vatican with the Catholic Church’s most powerful leaders until the process is complete, Lawrence finds himself at the center of a conspiracy that could lead to its downfall.",
                                                "en", "2024-01-01", 7.204, 2399, "/l4WXg5oQPK6GVlISKQNIUGb8rKJ.jpg",
                                                "/1YMrOtrW7b4pL2lfD8UciZPOJGs.jpg", 107.5437,
                                                "https://www.imdb.com/find?q=Conclave+2024&s=tt",
                                                "https://www.youtube.com/results?search_query=Conclave+trailer"),
                                new Movie("Moana 2", Arrays.asList("Animation", "Adventure", "Family", "Comedy"), "Unknown", Arrays.asList(), 2024,
                                                "Moana 2",
                                                "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
                                                "en", "2024-01-01", 7.077, 2336, "/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg",
                                                "/zo8CIjJ2nfNOevqNajwMRO6Hwka.jpg", 111.4736,
                                                "https://www.imdb.com/find?q=Moana+2+2024&s=tt",
                                                "https://www.youtube.com/results?search_query=Moana+2+trailer"),
                                new Movie("Day of Reckoning", Arrays.asList("Western", "Action"), "Unknown", Arrays.asList(),
                                                2025, "Day of Reckoning",
                                                "Put-upon lawman John Dorsey is on the verge of losing his wife and his job as sheriff, so he posses up with bullish U.S. Marshall Butch Hayden to hold outlaw Emily Rusk hostage. A battle of wills ensues as Emily turns the posse on themselves, but as her marauding husband and his gang approach, Emily and John realize they will need each other to survive.",
                                                "en", "2025-01-01", 6.7, 17, "/cVSjSQryFUERYSdOmdgJ2m0eBte.jpg",
                                                "/1hBtO9tXP60IFBZD27OsbaBmxs5.jpg", 99.5427,
                                                "https://www.imdb.com/find?q=Day+of+Reckoning+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Day+of+Reckoning+trailer"),
                                new Movie("Desert Dawn", Arrays.asList("Action", "Crime", "Mystery", "Thriller"), "Unknown", Arrays.asList(), 2025,
                                                "Desert Dawn",
                                                "A newly appointed small-town sheriff and his begrudging deputy get tangled up in a web of lies and corruption involving shady businessmen and the cartel while investigating the murder of a mysterious woman.",
                                                "en", "2025-01-01", 9.0, 3, "/S21BfLrJSD9njucBfY3CKqp8rD.jpg",
                                                "/bFmziv84NfEVEGTK8c6EVY3bxve.jpg", 99.0217,
                                                "https://www.imdb.com/find?q=Desert+Dawn+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Desert+Dawn+trailer"),
                                new Movie("The Glenarma Tapes", Arrays.asList("Horror"), "Unknown", Arrays.asList(),
                                                2024, "The Glenarma Tapes",
                                                "In Spring 2020 when five students and two faculty members from the Mid Ulster College of Art go missing in a forest on the north coast of Ireland. What happened on the day they disappeared has remained a mystery - until now.",
                                                "en", "2024-01-01", 6.1, 12, "/m0kojZkP1vcK9F8XSWfw9haJHKz.jpg",
                                                "/nyZjhvcmeXcr8H2Xx6JzKEAxPph.jpg", 96.6311,
                                                "https://www.imdb.com/find?q=The+Glenarma+Tapes+2024&s=tt",
                                                "https://www.youtube.com/results?search_query=The+Glenarma+Tapes+trailer"),
                                new Movie("Nonnas", Arrays.asList("Comedy"), "Unknown", Arrays.asList(), 2025,
                                                "Nonnas",
                                                "After losing his beloved mother, a man risks everything to honor her by opening an Italian restaurant with actual nonnas — grandmothers — as the chefs.",
                                                "en", "2025-01-01", 6.632, 38, "/lZEOKj5wtgUGpaQkzJRl7cjEv21.jpg",
                                                "/gfe8onl8FhaJg4C47Kecj7CdNvf.jpg", 95.8984,
                                                "https://www.imdb.com/find?q=Nonnas+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Nonnas+trailer"),
                                new Movie("Justice League", Arrays.asList("Action", "Adventure", "Science Fiction"), "Unknown", Arrays.asList(), 2017,
                                                "Justice League",
                                                "Fuelled by his restored faith in humanity and inspired by Superman's selfless act, Bruce Wayne and Diana Prince assemble a team of metahumans consisting of Barry Allen, Arthur Curry and Victor Stone to face the catastrophic threat of Steppenwolf and the Parademons who are on the hunt for three Mother Boxes on Earth.",
                                                "en", "2017-01-01", 6.075, 13134, "/eifGNCSDuxJeS1loAXil5bIGgvC.jpg",
                                                "/2nyaeISu2xIxIgZYNpX4UayY8PN.jpg", 146.715,
                                                "https://www.imdb.com/find?q=Justice+League+2017&s=tt",
                                                "https://www.youtube.com/results?search_query=Justice+League+trailer"),
                                new Movie("Captain Marvel", Arrays.asList("Action", "Adventure", "Science Fiction"), "Unknown", Arrays.asList(), 2019,
                                                "Captain Marvel",
                                                "The story follows Carol Danvers as she becomes one of the universe’s most powerful heroes when Earth is caught in the middle of a galactic war between two alien races. Set in the 1990s, Captain Marvel is an all-new adventure from a previously unseen period in the history of the Marvel Cinematic Universe.",
                                                "en", "2019-01-01", 6.802, 16017, "/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg",
                                                "/qAzYK4YPSWDc7aa4R43LcwRIAyb.jpg", 76.9178,
                                                "https://www.imdb.com/find?q=Captain+Marvel+2019&s=tt",
                                                "https://www.youtube.com/results?search_query=Captain+Marvel+trailer"),
                                new Movie("Bullet Train Explosion", Arrays.asList("Action", "Thriller", "Crime", "Drama"), "Unknown",
                                                Arrays.asList(), 2025, "新幹線大爆破",
                                                "When panic erupts on a Tokyo-bound bullet train that will explode if it slows below 100 kph, authorities race against time to save everyone on board.",
                                                "ja", "2025-01-01", 6.877, 159, "/jmzxlDBwgvRbpPJzNQwizyn9UEn.jpg",
                                                "/Zes06xI18u47pblwRGTtqRm0R8.jpg", 88.6646,
                                                "https://www.imdb.com/find?q=Bullet+Train+Explosion+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Bullet+Train+Explosion+trailer"),
                                new Movie("Wonder Woman 1984", Arrays.asList("Action", "Adventure", "Fantasy"), "Unknown", Arrays.asList(),
                                                2020, "Wonder Woman 1984",
                                                "A botched store robbery places Wonder Woman in a global battle against a powerful and mysterious ancient force that puts her powers in jeopardy.",
                                                "en", "2020-01-01", 6.412, 8604, "/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
                                                "/XSTGtPVegdHD1xy5GPuK0tURTQ.jpg", 157.441,
                                                "https://www.imdb.com/find?q=Wonder+Woman+1984+2020&s=tt",
                                                "https://www.youtube.com/results?search_query=Wonder+Woman+1984+trailer"),
                                new Movie("Final Destination Bloodlines", Arrays.asList("Horror", "Mystery"), "Unknown",
                                                Arrays.asList(), 2025, "Final Destination Bloodlines",
                                                "Plagued by a violent recurring nightmare, college student Stefanie heads home to track down the one person who might be able to break the cycle and save her family from the grisly demise that inevitably awaits them all.",
                                                "en", "2025-01-01", 6.9, 30, "/cAoktVUBhGyULRoxV6mZ2LB3x7I.jpg",
                                                "/7wKnf6ILtRmKXV8eJWk0P6ZXnQ.jpg", 91.0611,
                                                "https://www.imdb.com/find?q=Final+Destination+Bloodlines+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Final+Destination+Bloodlines+trailer"),
                                new Movie("The Meg", Arrays.asList("Action", "Science Fiction", "Horror"), "Unknown", Arrays.asList(), 2018,
                                                "The Meg",
                                                "A deep sea submersible pilot revisits his past fears in the Mariana Trench, and accidentally unleashes the seventy foot ancestor of the Great White Shark believed to be extinct.",
                                                "en", "2018-01-01", 6.248, 7796, "/eyWICPcxOuTcDDDbTMOZawoOn8d.jpg",
                                                "/2uSCHUsmzb6KkQPFSxBQ7bgfJLE.jpg", 153.271,
                                                "https://www.imdb.com/find?q=The+Meg+2018&s=tt",
                                                "https://www.youtube.com/results?search_query=The+Meg+trailer"),
                                new Movie("Logan", Arrays.asList("Action", "Drama", "Science Fiction"), "Unknown", Arrays.asList(), 2017, "Logan",
                                                "In the near future, a weary Logan cares for an ailing Professor X in a hideout on the Mexican border. But Logan's attempts to hide from the world and his legacy are upended when a young mutant arrives, pursued by dark forces.",
                                                "en", "2017-01-01", 7.82, 19597, "/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg",
                                                "/9X7YweCJw3q8Mcf6GadxReFEksM.jpg", 140.0689,
                                                "https://www.imdb.com/find?q=Logan+2017&s=tt",
                                                "https://www.youtube.com/results?search_query=Logan+trailer"),
                                new Movie("The Siege", Arrays.asList("Action", "Thriller"), "Unknown", Arrays.asList(), 2023,
                                                "The Siege",
                                                "International assassin Walker is compromised during a mission and sent to a reassignment center for a new identity. During his stay at the facility, a ruthless assault team storms the compound searching for someone their boss has lost. Walker begrudgingly falls in with skilled hitwoman Elda and her mysterious ward Juliet in order to survive the night.",
                                                "en", "2023-01-01", 5.448, 48, "/hVh4hMzkXNLnScudbid6hDvjMPk.jpg",
                                                "/4eC0tsU9OxR3Adlo1yRJYUDraW9.jpg", 82.78,
                                                "https://www.imdb.com/find?q=The+Siege+2023&s=tt",
                                                "https://www.youtube.com/results?search_query=The+Siege+trailer"),
                                new Movie("Drop", Arrays.asList("Mystery", "Thriller"), "Unknown", Arrays.asList(), 2025, "Drop",
                                                "Violet, a widowed mother on her first date in years, arrives at an upscale restaurant where she is relieved that her date, Henry, is more charming and handsome than she expected. But their chemistry begins to curdle as Violet begins being irritated and then terrorized by a series of anonymous drops to her phone.",
                                                "en", "2025-01-01", 6.539, 281, "/dS2S5lpfgRIRQOb7LDCjNsQqKjp.jpg",
                                                "/2CcMG34v4PCynvxwmBUwVtNqsKL.jpg", 79.9908,
                                                "https://www.imdb.com/find?q=Drop+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Drop+trailer"),
                                new Movie("War for the Planet of the Apes", Arrays.asList("Drama", "Science Fiction", "War"), "Unknown",
                                                Arrays.asList(), 2017, "War for the Planet of the Apes",
                                                "Caesar and his apes are forced into a deadly conflict with an army of humans led by a ruthless Colonel. After the apes suffer unimaginable losses, Caesar wrestles with his darker instincts and begins his own mythic quest to avenge his kind. As the journey finally brings them face to face, Caesar and the Colonel are pitted against each other in an epic battle that will determine the fate of both their species and the future of the planet.",
                                                "en", "2017-01-01", 7.206, 9228, "/mMA1qhBFgZX8O36qPPTC016kQl1.jpg",
                                                "/ulMscezy9YX0bhknvJbZoUgQxO5.jpg", 140.7602,
                                                "https://www.imdb.com/find?q=War+for+the+Planet+of+the+Apes+2017&s=tt",
                                                "https://www.youtube.com/results?search_query=War+for+the+Planet+of+the+Apes+trailer"),
                                new Movie("Novocaine", Arrays.asList("Action", "Comedy", "Thriller"), "Unknown", Arrays.asList(), 2025,
                                                "Novocaine",
                                                "When the girl of his dreams is kidnapped, everyman Nate turns his inability to feel pain into an unexpected strength in his fight to get her back.",
                                                "en", "2025-01-01", 6.908, 719, "/xmMHGz9dVRaMY6rRAlEX4W0Wdhm.jpg",
                                                "/sNx1A3822kEbqeUxvo5A08o4N7o.jpg", 77.4032,
                                                "https://www.imdb.com/find?q=Novocaine+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Novocaine+trailer"),
                                new Movie("Wonder Woman", Arrays.asList("Action", "Adventure", "Fantasy"), "Unknown", Arrays.asList(), 2017,
                                                "Wonder Woman",
                                                "An Amazon princess comes to the world of Man in the grips of the First World War to confront the forces of evil and bring an end to human conflict.",
                                                "en", "2017-01-01", 7.217, 20208, "/v4ncgZjG2Zu8ZW5al1vIZTsSjqX.jpg",
                                                "/AaABt75ZzfMGrscUR2seabz4PEX.jpg", 62.9808,
                                                "https://www.imdb.com/find?q=Wonder+Woman+2017&s=tt",
                                                "https://www.youtube.com/results?search_query=Wonder+Woman+trailer"),
                                new Movie("Mufasa: The Lion King", Arrays.asList("Adventure", "Family", "Animation"), "Unknown", Arrays.asList(),
                                                2024, "Mufasa: The Lion King",
                                                "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
                                                "en", "2024-01-01", 7.409, 2079, "/lurEK87kukWNaHd0zYnsi3yzJrs.jpg",
                                                "/oHPoF0Gzu8xwK4CtdXDaWdcuZxZ.jpg", 82.8464,
                                                "https://www.imdb.com/find?q=Mufasa%3A+The+Lion+King+2024&s=tt",
                                                "https://www.youtube.com/results?search_query=Mufasa:+The+Lion+King+trailer"),
                                new Movie("Sonic the Hedgehog 3", Arrays.asList("Action", "Science Fiction", "Comedy", "Family"), "Unknown", Arrays.asList(),
                                                2024, "Sonic the Hedgehog 3",
                                                "Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before. With their abilities outmatched in every way, Team Sonic must seek out an unlikely alliance in hopes of stopping Shadow and protecting the planet.",
                                                "en", "2024-01-01", 7.727, 2522, "/d8Ryb8AunYAuycVKDp5HpdWPKgC.jpg",
                                                "/zOpe0eHsq0A2NvNyBbtT6sj53qV.jpg", 83.6703,
                                                "https://www.imdb.com/find?q=Sonic+the+Hedgehog+3+2024&s=tt",
                                                "https://www.youtube.com/results?search_query=Sonic+the+Hedgehog+3+trailer"),
                                new Movie("Karate Kid: Legends", Arrays.asList("Action", "Adventure", "Drama"), "Unknown", Arrays.asList(),
                                                2025, "Karate Kid: Legends",
                                                "After a family tragedy, kung fu prodigy Li Fong is uprooted from his home in Beijing and forced to move to New York City with his mother. When a new friend needs his help, Li enters a karate competition – but his skills alone aren't enough. Li's kung fu teacher Mr. Han enlists original Karate Kid Daniel LaRusso for help, and Li learns a new way to fight, merging their two styles into one for the ultimate martial arts showdown.",
                                                "en", "2025-01-01", 7.35, 10, "/ckI6bmQDvvGy20FPTIW1kfGKGRK.jpg",
                                                "/tGjo4L15aELqZGqQH3ThZQGMKmL.jpg", 91.4537,
                                                "https://www.imdb.com/find?q=Karate+Kid%3A+Legends+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Karate+Kid:+Legends+trailer"),
                                new Movie("No Time to Die", Arrays.asList("Action", "Thriller", "Adventure"), "Unknown", Arrays.asList(), 2021,
                                                "No Time to Die",
                                                "Bond has left active service and is enjoying a tranquil life in Jamaica. His peace is short-lived when his old friend Felix Leiter from the CIA turns up asking for help. The mission to rescue a kidnapped scientist turns out to be far more treacherous than expected, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.",
                                                "en", "2021-01-01", 7.4, 6506, "/iUgygt3fscRoKWCV1d0C7FbM9TP.jpg",
                                                "/bz7pwNGCbV576COsDcYN9MbEACC.jpg", 116.9871,
                                                "https://www.imdb.com/find?q=No+Time+to+Die+2021&s=tt",
                                                "https://www.youtube.com/results?search_query=No+Time+to+Die+trailer"),
                                new Movie("Alien: Covenant", Arrays.asList("Science Fiction", "Horror", "Thriller"), "Unknown", Arrays.asList(), 2017,
                                                "Alien: Covenant",
                                                "The crew of the colony ship Covenant, bound for a remote planet on the far side of the galaxy, discovers what they think is an uncharted paradise but is actually a dark, dangerous world.",
                                                "en", "2017-01-01", 6.156, 8876, "/zecMELPbU5YMQpC81Z8ImaaXuf9.jpg",
                                                "/2qluV8y79LnBBHaMpwewCjQ1Htk.jpg", 105.3005,
                                                "https://www.imdb.com/find?q=Alien%3A+Covenant+2017&s=tt",
                                                "https://www.youtube.com/results?search_query=Alien:+Covenant+trailer"),
                                new Movie("Blade Runner 2049", Arrays.asList("Science Fiction", "Drama"), "Unknown", Arrays.asList(),
                                                2017, "Blade Runner 2049",
                                                "Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos. K's discovery leads him on a quest to find Rick Deckard, a former LAPD blade runner who has been missing for 30 years.",
                                                "en", "2017-01-01", 7.6, 14108, "/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
                                                "/bMdSmfI0qwpAkvhAL7sqpjmwgf4.jpg", 57.7245,
                                                "https://www.imdb.com/find?q=Blade+Runner+2049+2017&s=tt",
                                                "https://www.youtube.com/results?search_query=Blade+Runner+2049+trailer"),
                                new Movie("The Accountant²", Arrays.asList("Crime", "Thriller", "Action"), "Unknown", Arrays.asList(), 2025,
                                                "The Accountant²",
                                                "When an old acquaintance is murdered, Wolff is compelled to solve the case. Realizing more extreme measures are necessary, Wolff recruits his estranged and highly lethal brother, Brax, to help. In partnership with Marybeth Medina, they uncover a deadly conspiracy, becoming targets of a ruthless network of killers who will stop at nothing to keep their secrets buried.",
                                                "en", "2025-01-01", 7.233, 146, "/kMDUS7VmFhb2coRfVBoGLR8ADBt.jpg",
                                                "/rdxdvXQGqCj2Vb7SvTL8gdxlSzI.jpg", 67.6315,
                                                "https://www.imdb.com/find?q=The+Accountant%C2%B2+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=The+Accountant²+trailer"),
                                new Movie("Hacksaw Ridge", Arrays.asList("Drama", "History", "War"), "Unknown", Arrays.asList(), 2016,
                                                "Hacksaw Ridge",
                                                "WWII American Army Medic Desmond T. Doss, who served during the Battle of Okinawa, refuses to kill people and becomes the first Conscientious Objector in American history to receive the Congressional Medal of Honor.",
                                                "en", "2016-01-01", 8.193, 14078, "/jhWbYeUNOA5zAb6ufK6pXQFXqTX.jpg",
                                                "/vDKRMZGFTKP9nQolzeSB1rB1w6p.jpg", 113.1905,
                                                "https://www.imdb.com/find?q=Hacksaw+Ridge+2016&s=tt",
                                                "https://www.youtube.com/results?search_query=Hacksaw+Ridge+trailer"),
                                new Movie("It Comes at Night", Arrays.asList("Drama", "Horror", "Mystery"), "Unknown", Arrays.asList(),
                                                2017, "It Comes at Night",
                                                "Secure within a desolate home as an unnatural threat terrorizes the world, a man has established a tenuous domestic order with his wife and son, but this will soon be put to test when a desperate young family arrives seeking refuge.",
                                                "en", "2017-01-01", 5.8, 2423, "/rNKJpFMlOZn5zkzBPZxEJrQn5Km.jpg",
                                                "/6h9pjTsWzaUWuUszHHbeI1JWE1.jpg", 68.6186,
                                                "https://www.imdb.com/find?q=It+Comes+at+Night+2017&s=tt",
                                                "https://www.youtube.com/results?search_query=It+Comes+at+Night+trailer"),
                                new Movie("Karol G: Tomorrow Was Beautiful", Arrays.asList("Music", "Documentary"), "Unknown",
                                                Arrays.asList(), 2025, "Karol G: Mañana fue muy bonito",
                                                "Karol G pulls back the curtain on her rise to stardom while navigating a sold-out stadium tour, creating new music and releasing a new album.",
                                                "es", "2025-01-01", 8.096, 57, "/5aXoQYwaQ7JJVUWclHAEXJgiS2M.jpg",
                                                "/kpyXnnyO7UiK7FZFHJ5Ae7DRAIF.jpg", 68.316,
                                                "https://www.imdb.com/find?q=Karol+G%3A+Tomorrow+Was+Beautiful+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Karol+G:+Tomorrow+Was+Beautiful+trailer"),
                                new Movie("G20", Arrays.asList("Action", "Mystery", "Drama"), "Unknown", Arrays.asList(), 2025, "G20",
                                                "After the G20 Summit is overtaken by terrorists, President Danielle Sutton must bring all her statecraft and military experience to defend her family and her fellow leaders.",
                                                "en", "2025-01-01", 6.6, 468, "/wv6oWAleCJZUk5htrGg413t3GCy.jpg",
                                                "/k32XKMjmXMGeydykD32jfER3BVI.jpg", 77.3089,
                                                "https://www.imdb.com/find?q=G20+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=G20+trailer"),
                                new Movie("Mission: Impossible - The Final Reckoning", Arrays.asList("Action", "Adventure", "Thriller"),
                                                "Unknown", Arrays.asList(), 2025,
                                                "Mission: Impossible - The Final Reckoning",
                                                "Ethan Hunt and the IMF team continue their search for the terrifying AI known as the Entity — which has infiltrated intelligence networks all over the globe — with the world's governments and a mysterious ghost from Ethan's past on their trail. Joined by new allies and armed with the means to shut the Entity down for good, Hunt is in a race against time to prevent the world as we know it from changing forever.",
                                                "en", "2025-01-01", 0.0, 0, "/z53D72EAOxGRqdr7KXXWp9dJiDe.jpg",
                                                "/7ONMDhnErvpkKvkZqM82ud7bzcT.jpg", 65.8784,
                                                "https://www.imdb.com/find?q=Mission%3A+Impossible+-+The+Final+Reckoning+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Mission:+Impossible+-+The+Final+Reckoning+trailer"),
                                new Movie("The Biggest Fan", Arrays.asList("Comedy"), "Unknown", Arrays.asList(), 2025,
                                                "La más fan",
                                                "Canceled in Hollywood, star Lana Cruz heads to her hometown for a comeback. Enter Polly, her fan-turned-frenemy. Can Lana dodge drama and reclaim her fame?",
                                                "es", "2025-01-01", 5.265, 17, "/wgUmsekYPOt9ZQ8ero91qRnmhQY.jpg",
                                                "/iznPd7PLnCBA1G50M4DuA9wvCIy.jpg", 65.7881,
                                                "https://www.imdb.com/find?q=The+Biggest+Fan+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=The+Biggest+Fan+trailer"),
                                new Movie("The Godfather", Arrays.asList("Drama", "Crime"), "Unknown", Arrays.asList(), 1972,
                                                "The Godfather",
                                                "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
                                                "en", "1972-01-01", 8.687, 21418, "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
                                                "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg", 92.2817,
                                                "https://www.imdb.com/find?q=The+Godfather+1972&s=tt",
                                                "https://www.youtube.com/results?search_query=The+Godfather+trailer"),
                                new Movie("Deadpool 2", Arrays.asList("Action", "Comedy", "Adventure"), "Unknown", Arrays.asList(), 2018,
                                                "Deadpool 2",
                                                "Wisecracking mercenary Deadpool battles the evil and powerful Cable and other bad guys to save a boy's life.",
                                                "en", "2018-01-01", 7.49, 18351, "/to0spRl1CMDvyUbOnbb4fTk3VAd.jpg",
                                                "/3P52oz9HPQWxcwHOwxtyrVV1LKi.jpg", 113.0865,
                                                "https://www.imdb.com/find?q=Deadpool+2+2018&s=tt",
                                                "https://www.youtube.com/results?search_query=Deadpool+2+trailer"),
                                new Movie("My Fault", Arrays.asList("Romance", "Drama"), "Unknown", Arrays.asList(), 2023,
                                                "Culpa mía",
                                                "Noah must leave her city, boyfriend, and friends to move into William Leister's mansion, the flashy and wealthy husband of her mother Rafaela. As a proud and independent 17 year old, Noah resists living in a mansion surrounded by luxury. However, it is there where she meets Nick, her new stepbrother, and the clash of their strong personalities becomes evident from the very beginning.",
                                                "es", "2023-01-01", 7.814, 3678, "/w46Vw536HwNnEzOa7J24YH9DPRS.jpg",
                                                "/oz4U9eA6ilYf1tyiVuGmkftdLac.jpg", 61.2601,
                                                "https://www.imdb.com/find?q=My+Fault+2023&s=tt",
                                                "https://www.youtube.com/results?search_query=My+Fault+trailer"),
                                new Movie("Oppenheimer", Arrays.asList("Drama", "History"), "Unknown", Arrays.asList(), 2023,
                                                "Oppenheimer",
                                                "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
                                                "en", "2023-01-01", 8.06, 10201, "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
                                                "/neeNHeXjMF5fXoCJRsOmkNGC7q.jpg", 89.7359,
                                                "https://www.imdb.com/find?q=Oppenheimer+2023&s=tt",
                                                "https://www.youtube.com/results?search_query=Oppenheimer+trailer"),
                                new Movie("The Gorge", Arrays.asList("Romance", "Science Fiction", "Thriller"), "Unknown", Arrays.asList(), 2025,
                                                "The Gorge",
                                                "Two highly trained operatives grow close from a distance after being sent to guard opposite sides of a mysterious gorge. When an evil below emerges, they must work together to survive what lies within.",
                                                "en", "2025-01-01", 7.718, 2542, "/7iMBZzVZtG0oBug4TfqDb9ZxAOa.jpg",
                                                "/9nhjGaFLKtddDPtPaX5EmKqsWdH.jpg", 69.9344,
                                                "https://www.imdb.com/find?q=The+Gorge+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=The+Gorge+trailer"),
                                new Movie("The Dark Tower", Arrays.asList("Fantasy", "Action", "Science Fiction"), "Unknown", Arrays.asList(), 2017,
                                                "The Dark Tower",
                                                "A boy haunted by visions of a parallel world aids its disillusioned guardian in preventing the destruction of the nexus of universes known as the Dark Tower.",
                                                "en", "2017-01-01", 5.771, 5218, "/i9GUSgddIqrroubiLsvvMRYyRy0.jpg",
                                                "/pVVobDO8cezhVPvwD6EBUN0g3mt.jpg", 98.6318,
                                                "https://www.imdb.com/find?q=The+Dark+Tower+2017&s=tt",
                                                "https://www.youtube.com/results?search_query=The+Dark+Tower+trailer"),
                                new Movie("Basic Instinct", Arrays.asList("Thriller", "Mystery"), "Unknown", Arrays.asList(), 1992,
                                                "Basic Instinct",
                                                "Catherine, a novelist with an insatiable sexual appetite, becomes a prime suspect when her boyfriend is brutally murdered -- a crime she had described in her latest story.",
                                                "en", "1992-01-01", 6.934, 4027, "/76Ts0yoHk8kVQj9MMnoMixhRWoh.jpg",
                                                "/zTwoyVOAc6XCLjYfzWER6oQgpbO.jpg", 94.1309,
                                                "https://www.imdb.com/find?q=Basic+Instinct+1992&s=tt",
                                                "https://www.youtube.com/results?search_query=Basic+Instinct+trailer"),
                                new Movie("Flight Risk", Arrays.asList("Action", "Thriller"), "Unknown", Arrays.asList(), 2025,
                                                "Flight Risk",
                                                "A U.S. Marshal escorts a government witness to trial after he's accused of getting involved with a mob boss, only to discover that the pilot who is transporting them is also a hitman sent to assassinate the informant. After they subdue him, they're forced to fly together after discovering that there are others attempting to eliminate them.",
                                                "en", "2025-01-01", 6.098, 691, "/q0bCG4NX32iIEsRFZqRtuvzNCyZ.jpg",
                                                "/hwlyY7LJdEFbCPaGNXiskKKmJ5X.jpg", 60.3336,
                                                "https://www.imdb.com/find?q=Flight+Risk+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Flight+Risk+trailer"),
                                new Movie("The Woman in the Yard", Arrays.asList("Horror", "Mystery"), "Unknown", Arrays.asList(),
                                                2025, "The Woman in the Yard",
                                                "In the aftermath of her husband's death, widow Ramona's struggle to raise her two kids is hindered by the arrival of a mysterious woman with supernatural abilities.",
                                                "en", "2025-01-01", 6.243, 150, "/n0WS2TsNcS6dtaZKzxipyO7LuCJ.jpg",
                                                "/3lEV4CoKoeT2cZ4fbKEJugZcw6Z.jpg", 57.4765,
                                                "https://www.imdb.com/find?q=The+Woman+in+the+Yard+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=The+Woman+in+the+Yard+trailer"),
                                new Movie("Doctor Strange in the Multiverse of Madness", Arrays.asList("Fantasy", "Action", "Adventure"),
                                                "Unknown", Arrays.asList(), 2022,
                                                "Doctor Strange in the Multiverse of Madness",
                                                "Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.",
                                                "en", "2022-01-01", 7.261, 9513, "/ddJcSKbcp4rKZTmuyWaMhuwcfMz.jpg",
                                                "/iKUwhA4DUxMcNKu5lLSbDFwwilk.jpg", 90.9167,
                                                "https://www.imdb.com/find?q=Doctor+Strange+in+the+Multiverse+of+Madness+2022&s=tt",
                                                "https://www.youtube.com/results?search_query=Doctor+Strange+in+the+Multiverse+of+Madness+trailer"),
                                new Movie("John Wick: Chapter 3 - Parabellum", Arrays.asList("Action", "Thriller", "Crime"), "Unknown",
                                                Arrays.asList(), 2019, "John Wick: Chapter 3 - Parabellum",
                                                "Super-assassin John Wick returns with a $14 million price tag on his head and an army of bounty-hunting killers on his trail. After killing a member of the shadowy international assassin’s guild, the High Table, John Wick is excommunicado, but the world’s most ruthless hit men and women await his every turn.",
                                                "en", "2019-01-01", 7.443, 10947, "/ziEuG1essDuWuC5lpWUaw1uXY2O.jpg",
                                                "/vVpEOvdxVBP2aV166j5Xlvb5Cdc.jpg", 98.4376,
                                                "https://www.imdb.com/find?q=John+Wick%3A+Chapter+3+-+Parabellum+2019&s=tt",
                                                "https://www.youtube.com/results?search_query=John+Wick:+Chapter+3+-+Parabellum+trailer"),
                                new Movie("Wind River", Arrays.asList("Crime", "Mystery", "Thriller"), "Unknown", Arrays.asList(), 2017,
                                                "Wind River",
                                                "An FBI agent teams with the town's veteran game tracker to investigate a murder that occurred on a Native American reservation.",
                                                "en", "2017-01-01", 7.437, 5366, "/pySivdR845Hom4u4T2WNkJxe6Ad.jpg",
                                                "/kQGxGXzYiCumY8kmXXpgbZyZQK8.jpg", 92.6744,
                                                "https://www.imdb.com/find?q=Wind+River+2017&s=tt",
                                                "https://www.youtube.com/results?search_query=Wind+River+trailer"),
                                new Movie("The Sloth Lane", Arrays.asList("Animation", "Family"), "Unknown", Arrays.asList(), 2024,
                                                "The Sloth Lane",
                                                "After a terrifying storm destroys their home, a speedy sloth named Laura and her kooky family move to the big city in their rusted old food truck, Gordito, hoping to make their business a success. The family's delicious food catches the eye of a quick-witted cheetah who will stop at nothing to revive her failing fast-food business.",
                                                "en", "2024-01-01", 6.5, 16, "/toBN1A9AnhoUzXyu9gaVyQVJehp.jpg",
                                                "/lNQD8NdJ37winY0xEwjp9hUFqLX.jpg", 55.9335,
                                                "https://www.imdb.com/find?q=The+Sloth+Lane+2024&s=tt",
                                                "https://www.youtube.com/results?search_query=The+Sloth+Lane+trailer"),
                                new Movie("Ask Me What You Want", Arrays.asList("Romance", "Drama"), "Unknown", Arrays.asList(),
                                                2024, "Pídeme lo que quieras",
                                                "After his father's death, Eric Zimmerman travels to Spain to oversee his company's branches. In Madrid, he falls for Judith and engage in an intense, erotic relationship full of exploration. However, Eric fears his secret may end their affair.",
                                                "es", "2024-01-01", 5.997, 164, "/k82T5L1utX1G2LhNWeza9nGUKPk.jpg",
                                                "/qiVrapzgrDO7c6yQTSvn0dhwsn8.jpg", 57.921,
                                                "https://www.imdb.com/find?q=Ask+Me+What+You+Want+2024&s=tt",
                                                "https://www.youtube.com/results?search_query=Ask+Me+What+You+Want+trailer"),
                                new Movie("Star Wars: The Rise of Skywalker", Arrays.asList("Adventure", "Action", "Science Fiction"), "Unknown",
                                                Arrays.asList(), 2019, "Star Wars: The Rise of Skywalker",
                                                "The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.",
                                                "en", "2019-01-01", 6.3, 10172, "/db32LaOibwEliAmSL2jjDF6oDdj.jpg",
                                                "/auJKGst3vXpJozHZh4nMFs0xWIU.jpg", 87.663,
                                                "https://www.imdb.com/find?q=Star+Wars%3A+The+Rise+of+Skywalker+2019&s=tt",
                                                "https://www.youtube.com/results?search_query=Star+Wars:+The+Rise+of+Skywalker+trailer"),
                                new Movie("Devara: Part 1", Arrays.asList("Action", "Drama"), "Unknown", Arrays.asList(), 2024,
                                                "Devara: Part 1",
                                                "Devara, a fearless man from a coastal region, embarks on a perilous journey into the treacherous world of the sea to safeguard the lives of his people. Unbeknownst to him, his brother Bhaira is plotting a conspiracy against him. As events unfold, Devara passes on his legacy to his mild-mannered and timid son, Varada.",
                                                "te", "2024-01-01", 6.995, 192, "/1105WNYals12Va2f4F3VeBZdcWX.jpg",
                                                "/hAQnXxOwCjgYcKRgTdYPRC8neqL.jpg", 54.8346,
                                                "https://www.imdb.com/find?q=Devara%3A+Part+1+2024&s=tt",
                                                "https://www.youtube.com/results?search_query=Devara:+Part+1+trailer"),
                                new Movie("Parasite", Arrays.asList("Comedy", "Thriller", "Drama"), "Unknown", Arrays.asList(), 2019, "기생충",
                                                "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
                                                "ko", "2019-01-01", 8.5, 19015, "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
                                                "/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg", 52.7066,
                                                "https://www.imdb.com/find?q=Parasite+2019&s=tt",
                                                "https://www.youtube.com/results?search_query=Parasite+trailer"),
                                new Movie("Mission: Impossible - Fallout", Arrays.asList("Action", "Adventure"), "Unknown",
                                                Arrays.asList(), 2018, "Mission: Impossible - Fallout",
                                                "When an IMF mission ends badly, the world is faced with dire consequences. As Ethan Hunt takes it upon himself to fulfill his original briefing, the CIA begin to question his loyalty and his motives. The IMF team find themselves in a race against time, hunted by assassins while trying to prevent a global catastrophe.",
                                                "en", "2018-01-01", 7.431, 8465, "/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg",
                                                "/aw4FOsWr2FY373nKSxbpNi3fz4F.jpg", 86.1254,
                                                "https://www.imdb.com/find?q=Mission%3A+Impossible+-+Fallout+2018&s=tt",
                                                "https://www.youtube.com/results?search_query=Mission:+Impossible+-+Fallout+trailer"),
                                new Movie("Venom: The Last Dance", Arrays.asList("Action", "Science Fiction", "Adventure"), "Unknown", Arrays.asList(),
                                                2024, "Venom: The Last Dance",
                                                "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
                                                "en", "2024-01-01", 6.8, 3299, "/vGXptEdgZIhPg3cGlc7e8sNPC2e.jpg",
                                                "/3V4kLQg0kSqPLctI5ziYWabAZYF.jpg", 57.247,
                                                "https://www.imdb.com/find?q=Venom%3A+The+Last+Dance+2024&s=tt",
                                                "https://www.youtube.com/results?search_query=Venom:+The+Last+Dance+trailer"),
                                new Movie("Sex Education Mistresses", Arrays.asList("Comedy"), "Unknown",
                                                Arrays.asList(), 1973, "性教育ママ",
                                                "An erotic comedy depicting the sex adventures of  young wives living in an apartment complex, that are not satisfied with just having sex with their husbands.",
                                                "ja", "1973-01-01", 5.9, 5, "/xghWMg0pkBOdLHCTESyeyHU68wl.jpg",
                                                "None", 48.4795,
                                                "https://www.imdb.com/find?q=Sex+Education+Mistresses+1973&s=tt",
                                                "https://www.youtube.com/results?search_query=Sex+Education+Mistresses+trailer"),
                                new Movie("Fast & Furious Presents: Hobbs & Shaw", Arrays.asList("Action", "Adventure", "Comedy"), "Unknown",
                                                Arrays.asList(), 2019, "Fast & Furious Presents: Hobbs & Shaw",
                                                "Ever since US Diplomatic Security Service Agent Hobbs and lawless outcast Shaw first faced off, they just have traded smack talk and body blows. But when cyber-genetically enhanced anarchist Brixton's ruthless actions threaten the future of humanity, they join forces to defeat him.",
                                                "en", "2019-01-01", 6.847, 7366, "/qRyy2UmjC5ur9bDi3kpNNRCc5nc.jpg",
                                                "/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg", 84.4528,
                                                "https://www.imdb.com/find?q=Fast+%26+Furious+Presents%3A+Hobbs+%26+Shaw+2019&s=tt",
                                                "https://www.youtube.com/results?search_query=Fast+&+Furious+Presents:+Hobbs+&+Shaw+trailer"),
                                new Movie("Phineas and Ferb The Movie: Across the 2nd Dimension",
                                                Arrays.asList("Unknown"), "Unknown", Arrays.asList(), 2011,
                                                "Phineas and Ferb The Movie: Across the 2nd Dimension",
                                                "Phineas and Ferb get trapped in an alternate dimension where the evil Doofenshmirtz rules the tri-state area. They must find a way back home with the help of their pet platypus named Perry, who they discover is a secret agent.",
                                                "en", "2011-01-01", 7.077, 566, "/updMFSOZwEftfkJRpozwBlRlYI2.jpg",
                                                "/uxezSInaPoH20CyHx4TuY1LzGly.jpg", 47.1297,
                                                "https://www.imdb.com/find?q=Phineas+and+Ferb+The+Movie%3A+Across+the+2nd+Dimension+2011&s=tt",
                                                "https://www.youtube.com/results?search_query=Phineas+and+Ferb+The+Movie:+Across+the+2nd+Dimension+trailer"),
                                new Movie("Gunslingers", Arrays.asList("Western", "Action"), "Unknown", Arrays.asList(), 2025,
                                                "Gunslingers",
                                                "When the most wanted man in America surfaces in a small Kentucky town, his violent history -- and a blood-thirsty mob seeking vengeance and a king’s ransom -- soon follow. As brothers face off against one another and bullets tear the town to shreds, this lightning-fast gunslinger makes his enemies pay the ultimate price for their greed.",
                                                "en", "2025-01-01", 6.48, 50, "/O7REXWPANWXvX2jhQydHjAq2DV.jpg",
                                                "/zksO4lVnRKRoaSYzh2EDn2Z3Pel.jpg", 48.3506,
                                                "https://www.imdb.com/find?q=Gunslingers+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Gunslingers+trailer"),
                                new Movie("Swarm", Arrays.asList("Drama"), "Unknown", Arrays.asList(), 2023, "Rój",
                                                "A secluded island somewhere on a seas of the Northern Europe. A family of four has lived here for over ten years, perfecting the art of survival. They had moved onto an island to escape a falling civilization, to live in freedom, close to nature.  But, things can’t be solved by simply escaping the world, and problems arise when the Mother becomes pregnant again. Moreover, Winter is coming. It seems the only solution is in leaving the island, but this meets with stern dissent from the Father, who sees the place as the only safe haven on earth. Will the others find the courage to stand up to the Father? Can their family survive what comes next?",
                                                "pl", "2023-01-01", 4.5, 2, "/6Cmu2RgUd7u5Bk8AaKZktLbxMbW.jpg",
                                                "/q2DZEtjm6ZXqy43nnWVzkP59EBk.jpg", 44.4963,
                                                "https://www.imdb.com/find?q=Swarm+2023&s=tt",
                                                "https://www.youtube.com/results?search_query=Swarm+trailer"),
                                new Movie("Deadpool & Wolverine", Arrays.asList("Action", "Comedy", "Science Fiction"), "Unknown", Arrays.asList(),
                                                2024, "Deadpool & Wolverine",
                                                "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
                                                "en", "2024-01-01", 7.598, 7186, "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
                                                "/by8z9Fe8y7p4jo2YlW2SZDnptyT.jpg", 53.5471,
                                                "https://www.imdb.com/find?q=Deadpool+%26+Wolverine+2024&s=tt",
                                                "https://www.youtube.com/results?search_query=Deadpool+&+Wolverine+trailer"),
                                new Movie("The Super Mario Bros. Movie", Arrays.asList("Family", "Comedy", "Adventure", "Animation"), "Unknown",
                                                Arrays.asList(), 2023, "The Super Mario Bros. Movie",
                                                "While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.",
                                                "en", "2023-01-01", 7.622, 9665, "/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
                                                "/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg", 74.5865,
                                                "https://www.imdb.com/find?q=The+Super+Mario+Bros.+Movie+2023&s=tt",
                                                "https://www.youtube.com/results?search_query=The+Super+Mario+Bros.+Movie+trailer"),
                                new Movie("The Suicide Squad", Arrays.asList("Action", "Comedy", "Adventure"), "Unknown", Arrays.asList(),
                                                2021, "The Suicide Squad",
                                                "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
                                                "en", "2021-01-01", 7.488, 8879, "/q61qEyssk2ku3okWICKArlAdhBn.jpg",
                                                "/rAgsOIhqRS6tUthmHoqnqh9PIAE.jpg", 47.0011,
                                                "https://www.imdb.com/find?q=The+Suicide+Squad+2021&s=tt",
                                                "https://www.youtube.com/results?search_query=The+Suicide+Squad+trailer"),
                                new Movie("Hellraiser", Arrays.asList("Horror", "Mystery"), "Unknown", Arrays.asList(), 2022,
                                                "Hellraiser",
                                                "A young woman struggling with addiction comes into possession of an ancient puzzle box, unaware that its purpose is to summon the Cenobites, a group of sadistic supernatural beings from another dimension.",
                                                "en", "2022-01-01", 6.2, 872, "/f9ZAIUxTTk23vo1BC9Ur1Rx5c2E.jpg",
                                                "/4o0R4OdnRobrpVq1xYmj6aJyM7e.jpg", 50.4149,
                                                "https://www.imdb.com/find?q=Hellraiser+2022&s=tt",
                                                "https://www.youtube.com/results?search_query=Hellraiser+trailer"),
                                new Movie("Un lío de millones", Arrays.asList("Comedy"), "Unknown", Arrays.asList(),
                                                2024, "Un lío de millones",
                                                "In a village in the Sierra de Madrid, a couple feels that their children, who have since moved out, have forgotten about them. To get them back, they will pretend that they have won the lottery and that they are multimillionaires.",
                                                "es", "2024-01-01", 6.0, 15, "/1gPOV4ExV0AAGMLpF3em6BSRVV8.jpg",
                                                "/9JqrqquYOarMFb3O4j6gdJZG36K.jpg", 50.2116,
                                                "https://www.imdb.com/find?q=Un+l%C3%ADo+de+millones+2024&s=tt",
                                                "https://www.youtube.com/results?search_query=Un+lío+de+millones+trailer"),
                                new Movie("Flame of Recca: Final Burning", Arrays.asList("Animation", "Action"), "Unknown",
                                                Arrays.asList(), 2004, "烈火の炎 FINAL BURNING",
                                                "A retold ending based on the final few chapters of the Flame of Recca manga series.",
                                                "ja", "2004-01-01", 9.5, 3, "/mz4JRlydPga303keGQh5Ib0rLDC.jpg",
                                                "None", 46.6826,
                                                "https://www.imdb.com/find?q=Flame+of+Recca%3A+Final+Burning+2004&s=tt",
                                                "https://www.youtube.com/results?search_query=Flame+of+Recca:+Final+Burning+trailer"),
                                new Movie("Mulan", Arrays.asList("Adventure", "Fantasy", "Action", "Family"), "Unknown", Arrays.asList(), 2020, "Mulan",
                                                "When the Emperor of China issues a decree that one man per family must serve in the Imperial Chinese Army to defend the country from Huns, Hua Mulan, the eldest daughter of an honored warrior, steps in to take the place of her ailing father. She is spirited, determined and quick on her feet. Disguised as a man by the name of Hua Jun, she is tested every step of the way and must harness her innermost strength and embrace her true potential.",
                                                "en", "2020-01-01", 6.866, 6773, "/aKx1ARwG55zZ0GpRvU2WrGrCG9o.jpg",
                                                "/zMrk2G3XsnfYKiIp1NEfdtvDyBH.jpg", 80.7628,
                                                "https://www.imdb.com/find?q=Mulan+2020&s=tt",
                                                "https://www.youtube.com/results?search_query=Mulan+trailer"),
                                new Movie("Until Dawn", Arrays.asList("Horror", "Mystery"), "Unknown", Arrays.asList(), 2025,
                                                "Until Dawn",
                                                "One year after her sister Melanie mysteriously disappeared, Clover and her friends head into the remote valley where she vanished in search of answers. Exploring an abandoned visitor center, they find themselves stalked by a masked killer and horrifically murdered one by one...only to wake up and find themselves back at the beginning of the same evening.",
                                                "en", "2025-01-01", 6.5, 144, "/6O9nkcmZBymDXtxOGJmulqcxJdv.jpg",
                                                "/3xKJ0nyUTlySmMBCpOcsuSnFPI1.jpg", 48.4141,
                                                "https://www.imdb.com/find?q=Until+Dawn+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Until+Dawn+trailer"),
                                new Movie("Death Wish", Arrays.asList("Action", "Crime", "Thriller", "Drama"), "Unknown", Arrays.asList(), 2018,
                                                "Death Wish",
                                                "A mild-mannered father is transformed into a killing machine after his family is torn apart by a violent act.",
                                                "en", "2018-01-01", 6.188, 2607, "/g0eEEZAqMf98ULQnoiORuazjOpn.jpg",
                                                "/uQqQvmptJLPTcWDrZXn22p7j7s3.jpg", 83.3467,
                                                "https://www.imdb.com/find?q=Death+Wish+2018&s=tt",
                                                "https://www.youtube.com/results?search_query=Death+Wish+trailer"),
                                new Movie("Despicable Me 4", Arrays.asList("Animation", "Family", "Comedy", "Science Fiction"), "Unknown", Arrays.asList(), 2024,
                                                "Despicable Me 4",
                                                "Gru and Lucy and their girls—Margo, Edith and Agnes—welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Gru also faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
                                                "en", "2024-01-01", 7.047, 2747, "/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
                                                "/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg", 47.6636,
                                                "https://www.imdb.com/find?q=Despicable+Me+4+2024&s=tt",
                                                "https://www.youtube.com/results?search_query=Despicable+Me+4+trailer"),
                                new Movie("Locked", Arrays.asList("Thriller"), "Unknown", Arrays.asList(), 2025,
                                                "Locked",
                                                "When Eddie breaks into a luxury SUV, he steps into a deadly trap set by William, a self-proclaimed vigilante delivering his own brand of twisted justice. With no means of escape, Eddie must fight to survive in a ride where escape is an illusion, survival is a nightmare, and justice shifts into high gear.",
                                                "en", "2025-01-01", 6.209, 122, "/hhkiqXpfpufwxVrdSftzeKIANl3.jpg",
                                                "/r4X2xRrWleVgx0kahP27xRmm3ia.jpg", 49.9442,
                                                "https://www.imdb.com/find?q=Locked+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Locked+trailer"),
                                new Movie("Memoir of a Snail", Arrays.asList("Animation", "Drama", "Comedy"), "Unknown", Arrays.asList(),
                                                2024, "Memoir of a Snail",
                                                "Forcibly separated from her twin brother when they are orphaned, a melancholic misfit learns how to find confidence within herself amid the clutter of misfortunes and everyday life.",
                                                "en", "2024-01-01", 8.058, 480, "/57AgZv1ITeBLShiNdchZ5153evs.jpg",
                                                "/jl2YIADk391yc6Qjy9JhgCRkHJk.jpg", 50.1399,
                                                "https://www.imdb.com/find?q=Memoir+of+a+Snail+2024&s=tt",
                                                "https://www.youtube.com/results?search_query=Memoir+of+a+Snail+trailer"),
                                new Movie("Inside Out 2", Arrays.asList("Animation", "Adventure", "Comedy", "Family"), "Unknown", Arrays.asList(), 2024,
                                                "Inside Out 2",
                                                "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
                                                "en", "2024-01-01", 7.557, 5815, "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
                                                "/p5ozvmdgsmbWe0H8Xk7Rc8SCwAB.jpg", 47.2258,
                                                "https://www.imdb.com/find?q=Inside+Out+2+2024&s=tt",
                                                "https://www.youtube.com/results?search_query=Inside+Out+2+trailer"),
                                new Movie("Casino Royale", Arrays.asList("Adventure", "Action", "Thriller"), "Unknown", Arrays.asList(), 2006,
                                                "Casino Royale",
                                                "Le Chiffre, a banker to the world's terrorists, is scheduled to participate in a high-stakes poker game in Montenegro, where he intends to use his winnings to establish his financial grip on the terrorist market. M sends Bond—on his maiden mission as a 00 Agent—to attend this game and prevent Le Chiffre from winning. With the help of Vesper Lynd and Felix Leiter, Bond enters the most important poker game in his already dangerous career.",
                                                "en", "2006-01-01", 7.558, 10953, "/lMrxYKKhd4lqRzwUHAy5gcx9PSO.jpg",
                                                "/klJMCIblHLFwCuGjKz7tyOpekIC.jpg", 74.4726,
                                                "https://www.imdb.com/find?q=Casino+Royale+2006&s=tt",
                                                "https://www.youtube.com/results?search_query=Casino+Royale+trailer"),
                                new Movie("The Wild Robot", Arrays.asList("Animation", "Science Fiction", "Family"), "Unknown", Arrays.asList(), 2024,
                                                "The Wild Robot",
                                                "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
                                                "en", "2024-01-01", 8.319, 4873, "/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg",
                                                "/1pmXyN3sKeYoUhu5VBZiDU4BX21.jpg", 47.3038,
                                                "https://www.imdb.com/find?q=The+Wild+Robot+2024&s=tt",
                                                "https://www.youtube.com/results?search_query=The+Wild+Robot+trailer"),
                                new Movie("Ash", Arrays.asList("Science Fiction", "Horror", "Thriller"), "Unknown", Arrays.asList(), 2025, "Ash",
                                                "A woman wakes up on a distant planet and finds the crew of her space station viciously killed. Her investigation into what happened sets in motion a terrifying chain of events.",
                                                "en", "2025-01-01", 5.339, 217, "/nRa8B3tQCUK6pVwjasIyQehbvpF.jpg",
                                                "/sQa299yggIkxfwKJFgzYwDdsC9t.jpg", 41.3834,
                                                "https://www.imdb.com/find?q=Ash+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Ash+trailer"),
                                new Movie("Cleaner", Arrays.asList("Action", "Thriller"), "Unknown", Arrays.asList(), 2025,
                                                "Cleaner",
                                                "When a group of radical activists take over an energy company's annual gala, seizing 300 hostages, an ex-soldier turned window cleaner suspended 50 storeys up on the outside of the building must save those trapped inside, including her younger brother.",
                                                "en", "2025-01-01", 6.643, 249, "/mwzDApMZAGeYCEVjhegKvCzDX0W.jpg",
                                                "/2TtpJq1PbeQ36E5FnHVX4O6hVvu.jpg", 41.1425,
                                                "https://www.imdb.com/find?q=Cleaner+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Cleaner+trailer"),
                                new Movie("The Substance", Arrays.asList("Horror", "Science Fiction"), "Unknown", Arrays.asList(), 2024,
                                                "The Substance",
                                                "A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.",
                                                "en", "2024-01-01", 7.146, 4555, "/evdF1vmLzuzH8EFblqAXBXWRGSi.jpg",
                                                "/pRjCDn51n9otE0AzpGRYGVWP1LB.jpg", 46.735,
                                                "https://www.imdb.com/find?q=The+Substance+2024&s=tt",
                                                "https://www.youtube.com/results?search_query=The+Substance+trailer"),
                                new Movie("Mickey 17", Arrays.asList("Science Fiction", "Comedy", "Adventure"), "Unknown", Arrays.asList(), 2025,
                                                "Mickey 17",
                                                "Unlikely hero Mickey Barnes finds himself in the extraordinary circumstance of working for an employer who demands the ultimate commitment to the job… to die, for a living.",
                                                "en", "2025-01-01", 6.896, 1876, "/edKpE9B5qN3e559OuMCLZdW1iBZ.jpg",
                                                "/qUc0Hol3eP74dbW4YyqT6oRLYgT.jpg", 52.3381,
                                                "https://www.imdb.com/find?q=Mickey+17+2025&s=tt",
                                                "https://www.youtube.com/results?search_query=Mickey+17+trailer"),
                                new Movie("Kraven the Hunter", Arrays.asList("Action", "Adventure", "Thriller"), "Unknown", Arrays.asList(),
                                                2024, "Kraven the Hunter",
                                                "Kraven Kravinoff's complex relationship with his ruthless gangster father, Nikolai, starts him down a path of vengeance with brutal consequences, motivating him to become not only the greatest hunter in the world, but also one of its most feared.",
                                                "en", "2024-01-01", 6.578, 1657, "/1GvBhRxY6MELDfxFrete6BNhBB5.jpg",
                                                "/v9Du2HC3hlknAvGlWhquRbeifwW.jpg", 46.9906,
                                                "https://www.imdb.com/find?q=Kraven+the+Hunter+2024&s=tt",
                                                "https://www.youtube.com/results?search_query=Kraven+the+Hunter+trailer")
                };

                for (Movie movie : movies) {
                        controller.addMovie(movie);
                }
        }
}
